'use strict';
const KEY='home-sweet-home-v1';
const DAYS=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
const ROUTINE={0:['Plan three family dinners','Prepare daycare items for Monday','Reset kitchen for the week'],1:['Clear kitchen and dining clutter','Wipe counters and stove','Sweep kitchen floor'],2:['Wipe bathroom sinks and counters','Clean toilets in all 3 bathrooms','Wipe mirrors and replace towels'],3:['Pick up clothes in both bedrooms','Vacuum upstairs carpet (bedrooms, loft and hall)','Gather dirty laundry'],4:['Pick up toys and items from downstairs floors','Check Shark clean-water tank if needed','Shark cleans automatically overnight — clear floors for it','Put trash bins out Thursday evening'],5:['Bring trash bins in after pickup','Quick kitchen reset','Enjoy a lighter Friday'],6:['Finish one laundry load','Do one 30–45 minute decluttering session','Groceries and errands']};
const PROJECTS=[['Kitchen & bathrooms','Clear kitchen counters','Deep clean main bathroom','Deep clean second full bathroom','Deep clean downstairs half bath'],['Bedrooms','Reset your bedroom floor','Fold and put away clean clothes','Sort Bailey’s outgrown clothes','Organize Bailey’s dresser'],['Loft & guest room','Sort seasonal blankets and quilts','Store seasonal bedding','Sort guest room storage','Clear space for guest bed'],['Garage','Sort first batch of moving boxes','Set aside donations and trash','Sort remaining boxes','Create labeled storage zones']];
const MAINT=[['Check HVAC filter','Monthly; replace according to filter and lease guidance'],['Test smoke and CO alarms','Monthly; follow manufacturer instructions'],['Clean dishwasher filter','Monthly or as manufacturer recommends'],['Clean washing machine gasket/dispenser','Monthly'],['Check under sinks for leaks','Monthly'],['Clean dryer lint screen','After every load; check vent regularly'],['Check seasonal home upkeep','Spring and fall; ask landlord about responsibilities']];
const DEFAULT_MEALS=['Leftovers or easy dinner','Chicken tacos','Leftovers','Pasta and vegetables','Homemade pizza','Sheet-pan chicken and potatoes','Slow-cooker dinner'];
const blank=()=>({checks:{},projects:{},laundry:{},maintenance:{},meals:[...DEFAULT_MEALS],extra:[],notes:'',groceries:[],events:[],capture:[],supplies:[],decor:[],bailey:[],savedVerses:[],minimum:false,reminders:{},recipes:[]});
let state=load(),tab='home',selectedDay=new Date().getDay();
function load(){try{let raw=JSON.parse(localStorage.getItem(KEY));if(raw&&typeof raw==='object')return {...blank(),...raw,checks:raw.checks||{},projects:raw.projects||{},laundry:raw.laundry||{},maintenance:raw.maintenance||{},meals:Array.isArray(raw.meals)?raw.meals:[...DEFAULT_MEALS],extra:Array.isArray(raw.extra)?raw.extra:[],groceries:Array.isArray(raw.groceries)?raw.groceries:[],events:Array.isArray(raw.events)?raw.events:[],capture:Array.isArray(raw.capture)?raw.capture:[],supplies:Array.isArray(raw.supplies)?raw.supplies:[],decor:Array.isArray(raw.decor)?raw.decor:[],bailey:Array.isArray(raw.bailey)?raw.bailey:[],savedVerses:Array.isArray(raw.savedVerses)?raw.savedVerses:[],minimum:!!raw.minimum,reminders:raw.reminders||{},recipes:Array.isArray(raw.recipes)?raw.recipes:[]}}catch(e){}return blank()}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch(e){alert('Your browser could not save progress. Export a backup from More.')}}
function isoDate(d){return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')}
function dayDate(day){const now=new Date(),diff=day-now.getDay(),d=new Date(now.getFullYear(),now.getMonth(),now.getDate()+diff);return isoDate(d)}
function weekKey(d=new Date()){const a=new Date(d.getFullYear(),d.getMonth(),d.getDate()-((d.getDay()+6)%7));return isoDate(a)}
function esc(x){return String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function done(k){return !!state.checks[k]}
function task(label,key){return `<label class="task"><input type="checkbox" data-check="${esc(key)}" ${done(key)?'checked':''}><span>${esc(label)}</span></label>`}
function progress(n,total){return `<div class="progress"><div style="width:${total?Math.round(n/total*100):0}%"></div></div><p class="muted">${n} of ${total} complete</p>`}
function dayTasks(day){const date=dayDate(day);return ROUTINE[day].map((s,i)=>[s,'routine:'+date+':'+i]).concat(state.extra.filter(x=>x.day===day).map(x=>[x.label,'extra:'+date+':'+x.id]))}
function today(){const d=new Date().getDay(),t=dayTasks(d),count=t.filter(x=>done(x[1])).length;return `<div class="card hero"><div class="ornament">✿ · ♡ · ✿</div><div class="topline"><span class="eyebrow">TODAY'S LITTLE WINS</span><span class="pill">20 minutes</span></div><h2>${DAYS[d]}'s focus</h2>${t.map(x=>task(...x)).join('')}${progress(count,t.length)}<p class="subtle">Stop when your timer ends. Unfinished tasks do not pile onto tomorrow.</p></div><div class="grid"><div class="mini"><div>☀️</div><b>5:40 AM</b><small>20-minute reset</small></div><div class="mini"><div>♡</div><b>Evenings</b><small>Dinner and Bailey time</small></div><div class="mini"><div>♧</div><b>Laundry</b><small>Wed / Sat / Sun</small></div><div class="mini"><div>✧</div><b>Room reset</b><small>One project at a time</small></div></div><div class="sectionlabel">YOUR DAILY RHYTHM</div><div class="card"><p><b>5:40–6:00</b> · Quick cleaning</p><p><b>6:00–6:45</b> · Get yourself ready</p><p><b>6:45–7:30</b> · Wake and prepare Bailey</p><p><b>6:00–8:45 PM</b> · Dinner, play, bedtime</p><p><b>After 8:45 PM</b> · Your time — no assigned chores</p><div class="note">Aim for enough sleep. On exhausting mornings, a 5-minute reset is enough.</div></div>`}
function week(){const t=dayTasks(selectedDay),n=t.filter(x=>done(x[1])).length;return `<div class="card"><h2>Your weekly rhythm</h2><p class="subtle">Tap a day to see its morning assignment.</p><div class="days">${DAYS.map((x,i)=>`<button class="day ${selectedDay===i?'selected':''}" data-day="${i}">${x.slice(0,3)}</button>`).join('')}</div><h3>${DAYS[selectedDay]}</h3>${t.map(x=>task(...x)).join('')}${progress(n,t.length)}<div class="row-actions"><button class="button secondary" id="add-task">+ Add a task to this day</button></div></div><div class="card"><h3>Three laundry loads</h3><p class="subtle">Each step resets every Monday. Only count a load finished when it is put away.</p>${[ ['Wednesday','Clothes'],['Saturday','Clothes and towels'],['Sunday','Bedding / remaining clothes']].map((x,i)=>`<div class="sectionlabel">${x[0]} · ${x[1]}</div>${['Wash','Dry','Put away'].map((s,j)=>task(s,'laundry:'+weekKey()+':'+i+':'+j)).join('')}`).join('')}</div>`}
function reset(){let completed=0,total=0;PROJECTS.forEach((p,i)=>p.slice(1).forEach((_,j)=>{total++;if(state.projects[i+':'+j])completed++}));return `<div class="card peach"><h2>Room-by-room reset</h2><p class="subtle">One 30–45 minute Saturday session. The four-week plan can take longer if life gets busy.</p>${progress(completed,total)}</div>${PROJECTS.map((p,i)=>`<div class="card"><div class="topline"><h3>Week ${i+1} · ${esc(p[0])}</h3><span class="pill">${p.slice(1).filter((_,j)=>state.projects[i+':'+j]).length}/4</span></div>${p.slice(1).map((s,j)=>`<label class="task"><input type="checkbox" data-project="${i}:${j}" ${state.projects[i+':'+j]?'checked':''}><span>${esc(s)}</span></label>`).join('')}</div>`).join('')}`}
function plan(){return `<div class="card sage"><h2>Dinner for two ♡</h2><p class="subtle">One meal for you and Bailey. Three cooking nights, leftovers and easy dinners. Tap any meal to change it.</p></div><div class="card">${DAYS.map((d,i)=>`<div class="meal"><label class="caption" for="meal-${i}">${d}</label><input id="meal-${i}" class="field" data-meal="${i}" value="${esc(state.meals[i]||'')}"></div>`).join('')}<button class="button" id="save-meals">Save meal plan</button></div><div class="card"><h3>Grocery checklist</h3><p class="subtle">Add items as you think of them. Check them off while shopping.</p><div class="row-actions"><input id="new-grocery" class="field grow" maxlength="120" placeholder="Milk, bananas, chicken…"><button class="button" id="add-grocery">Add</button></div>${state.groceries.map((g,i)=>`<div class="grocery-line"><label class="task"><input type="checkbox" data-grocery="${i}" ${g.done?'checked':''}><span>${esc(g.label)}</span></label><button class="icon-button" aria-label="Remove item" data-remove-grocery="${i}">×</button></div>`).join('')}</div><div class="card"><h3>Grocery / dinner notes</h3><textarea id="notes" class="field" placeholder="Ingredients, groceries, quick meal ideas…">${esc(state.notes)}</textarea><div class="row-actions"><button class="button secondary" id="save-notes">Save notes</button></div></div>`}

function calendar(){const now=new Date(),start=new Date(now.getFullYear(),now.getMonth(),1),month=new Intl.DateTimeFormat('en-US',{month:'long',year:'numeric'}).format(now),offset=start.getDay(),last=new Date(now.getFullYear(),now.getMonth()+1,0).getDate();let cells='';for(let n=0;n<offset;n++)cells+='<div class="cal-empty"></div>';for(let d=1;d<=last;d++){const dt=new Date(now.getFullYear(),now.getMonth(),d),day=dt.getDay(),date=isoDate(dt),evt=state.events.filter(x=>x.date===date),isToday=date===isoDate(now);cells+=`<div class="cal-day ${isToday?'cal-today':''}"><b>${d}</b><small>${day===5?'Trash':day===4?'Bins':day===3?'Carpet':''}</small>${evt.map(x=>`<small class="cal-event">${esc(x.label)}</small>`).join('')}</div>`}return `<div class="card"><span class="eyebrow">THE LITTLE THINGS, PLANNED</span><h2>${month}</h2><p class="subtle">Weekly routines appear automatically. Add personal reminders below; this calendar does not send notifications.</p><div class="calendar">${['S','M','T','W','T','F','S'].map(x=>`<div class="cal-heading">${x}</div>`).join('')}${cells}</div></div><div class="card"><h3>Add a calendar note</h3><div class="row-actions"><input id="event-date" type="date" class="field grow" value="${isoDate(now)}"><input id="event-label" class="field grow" maxlength="100" placeholder="Filter check, appointment…"><button class="button" id="add-event">Add note</button></div>${state.events.filter(x=>x.date.slice(0,7)===isoDate(now).slice(0,7)).sort((a,b)=>a.date.localeCompare(b.date)).map(x=>`<div class="grocery-line"><span class="subtle">${esc(x.date)} · ${esc(x.label)}</span><button class="icon-button" data-remove-event="${esc(x.id)}" aria-label="Remove note">×</button></div>`).join('')}</div>`}
function more(){const month=new Date().toISOString().slice(0,7);return `<div class="card"><h2>Home maintenance</h2><p class="subtle">Monthly items reset each calendar month. Confirm maintenance responsibilities with your landlord.</p>${MAINT.map((x,i)=>`<label class="task"><input type="checkbox" data-maint="${month}:${i}" ${state.maintenance[month+':'+i]?'checked':''}><span><b>${esc(x[0])}</b><br><small class="muted">${esc(x[1])}</small></span></label>`).join('')}</div><div class="card"><h2>Your data</h2><p class="subtle">Your progress is stored on this device in this browser. It does not automatically sync across devices. Export a backup before clearing Safari data or changing phones.</p><div class="row-actions"><button class="button" id="export">Export backup</button><button class="button secondary" id="import">Import backup</button><input type="file" id="import-file" accept="application/json,.json" hidden></div></div><div class="card"><h3>Starting schedule</h3><p class="subtle">5:40–6:00 AM cleaning · 6:00–6:45 getting ready · 6:45–7:30 Bailey · Friday trash pickup · Saturdays for one decluttering project.</p><button class="button danger" id="clear">Erase all app data</button></div>`}

const VERSES=[
['Psalm 46:10','Be still, and know that I am God.','Peace','When the day is already moving fast, even one quiet moment can help you remember that God is near. You can be present with Bailey without finishing every chore.','Lord, settle my thoughts today. Help me notice the beautiful small moments with my son and trust You with what remains. Amen.'],
['Philippians 4:6','Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God.','Trust','You can bring every worry, big or small, to God, including the things you carry for Bailey.','Lord, meet me in my worries. Give me wisdom, peace, and a grateful heart as I care for Bailey. Amen.'],
['Isaiah 40:31','But they that wait upon the LORD shall renew their strength;','Strength','Some days require more energy than you have. Rest and renewed strength matter more than a perfect home.','God, renew my strength and patience today. Help me show Bailey tenderness, even when I feel tired. Amen.'],
['Proverbs 3:5','Trust in the LORD with all thine heart; and lean not unto thine own understanding.','Faith','You do not need every answer about tomorrow to love your child well today.','Lord, guide my decisions and steady my heart. Help me lead our little family with love. Amen.'],
['Psalm 118:24','This is the day which the LORD hath made; we will rejoice and be glad in it.','Joy','The small joys of motherhood count: a laugh, a hug, a silly moment in the kitchen.','Lord, open my eyes to joy today. Help Bailey and me make a sweet memory together. Amen.'],
['Colossians 3:13','Forbearing one another, and forgiving one another,','Grace','Patience is not always easy. A hard moment can become an opportunity to begin again gently.','Lord, help me respond with grace and apologize when I need to. Fill our home with kindness. Amen.'],
['James 1:5','If any of you lack wisdom, let him ask of God,','Wisdom','There are so many decisions to make as a parent. You are allowed to ask for guidance.','God, give me wisdom for the decisions I face and patience as I learn. Amen.']
];
function verseToday(){const n=Math.floor(new Date().setHours(0,0,0,0)/86400000);return VERSES[((n%VERSES.length)+VERSES.length)%VERSES.length]}
function grace(){const v=verseToday(),saved=state.savedVerses.includes(v[0]);return `<section class="card grace"><div class="eyebrow">✿ MORNING GRACE · ${esc(v[2].toUpperCase())}</div><div class="flourish">❀ ♡ ❀</div><blockquote>“${esc(v[1])}”</blockquote><p class="verse-ref">${esc(v[0])} · KJV</p><div class="grace-divider"></div><h3>♡ A reminder for your mama heart</h3><p>${esc(v[3])}</p><div class="prayer"><span class="eyebrow">TODAY'S LITTLE PRAYER</span><p>${esc(v[4])}</p></div><div class="row-actions"><button class="button secondary" id="save-verse">${saved?'♥ Saved verse':'♡ Save verse'}</button><button class="button secondary" id="copy-verse">Copy verse & prayer</button></div></section>`}
function inbox(){return `<div class="card"><h2>Quick Capture ✎</h2><p class="subtle">Remember it now, decide what to do with it later.</p><div class="row-actions"><input class="field grow" id="capture-input" placeholder="Something I need to remember…" maxlength="180"><button class="button" id="capture-add">Add</button></div>${state.capture.map((x,i)=>`<div class="grocery-line"><label class="task"><input type="checkbox" data-capture="${i}" ${x.done?'checked':''}><span>${esc(x.label)}</span></label><button class="icon-button" data-remove-capture="${i}" aria-label="Remove">×</button></div>`).join('')}</div>`}
function supplies(){return `<div class="card"><h2>Household supplies ♧</h2><p class="subtle">Track what needs restocking. Add it to your groceries with one tap.</p><div class="row-actions"><input id="supply-input" class="field grow" maxlength="100" placeholder="Diapers, detergent, wipes…"><button class="button" id="supply-add">Add</button></div>${state.supplies.map((x,i)=>`<div class="inventory-line"><span>${esc(x.label)}</span><select class="field" data-supply-status="${i}"><option ${x.status==='stocked'?'selected':''} value="stocked">Stocked</option><option ${x.status==='low'?'selected':''} value="low">Running low</option><option ${x.status==='out'?'selected':''} value="out">Out</option></select><button class="button secondary" data-supply-grocery="${i}">+ List</button><button class="icon-button" data-supply-remove="${i}">×</button></div>`).join('')}</div>`}
function collections(){return `<div class="card"><h2>Bailey's Corner ♡</h2><p class="subtle">Daycare notes, things to pack, sizes, and sweet little reminders. Keep sensitive information out of this local-only app.</p><div class="row-actions"><input id="bailey-input" class="field grow" maxlength="150" placeholder="Extra clothes for daycare…"><button class="button" data-add-collection="bailey">Add</button></div>${state.bailey.map((x,i)=>`<div class="grocery-line"><label class="task"><input data-collection-check="bailey:${i}" type="checkbox" ${x.done?'checked':''}><span>${esc(x.label)}</span></label><button class="icon-button" data-collection-remove="bailey:${i}">×</button></div>`).join('')}</div><div class="card"><h2>Seasonal storage ❀</h2><p class="subtle">Keep track of decor and which labeled bin holds it.</p><div class="row-actions"><input id="decor-input" class="field grow" maxlength="150" placeholder="Christmas garland — garage bin 3"><button class="button" data-add-collection="decor">Add</button></div>${state.decor.map((x,i)=>`<div class="grocery-line"><span class="grow">${esc(x.label)}</span><button class="icon-button" data-collection-remove="decor:${i}">×</button></div>`).join('')}</div>`}
function sunday(){return `<div class="card sage"><h2>Sunday Reset ☀</h2><p class="subtle">A gentle weekly check-in, not another huge chore list.</p>${['Choose dinners for the week','Check groceries and supplies','Plan three laundry loads','Check appointments and daycare needs','Pick one small decluttering project'].map((x,i)=>task(x,'sunday:'+weekKey()+':'+i)).join('')}</div>`}
function home(){const d=new Date().getDay(),tasks=dayTasks(d),items=state.minimum?tasks.slice(0,2):tasks;return `<div class="welcome"><span class="eyebrow">YOUR COZY LITTLE CORNER OF THE WORLD</span><h2>Good ${new Date().getHours()<12?'morning':new Date().getHours()<17?'afternoon':'evening'}, mama ♡</h2><p>Little steps. A whole lot of love.</p></div>${grace()}<div class="card hero"><div class="topline"><h2>Today's little wins</h2><span class="pill">${state.minimum?'Grace mode':'20 minutes'}</span></div>${items.map(x=>task(...x)).join('')}${progress(items.filter(x=>done(x[1])).length,items.length)}<button class="button secondary" id="minimum">${state.minimum?'Show regular routine':'♡ Bare Minimum Day'}</button><p class="subtle">${state.minimum?'Just the essentials today. Everything else can wait.':'Your Shark handles its nightly run automatically.'}</p></div><div class="grid"><div class="mini"><div>🍲</div><b>Tonight's dinner</b><small>${esc(state.meals[d]||'Plan something easy')}</small></div><div class="mini"><div>🧺</div><b>Laundry rescue</b><small>Wash · Dry · Fold · Put away</small></div></div>${inbox()}${d===0?sunday():''}`}
function lists(){return `<div class="card peach"><h2>Little lists, less to remember ♡</h2><p class="subtle">Shopping and household supplies in one cozy place.</p></div><div class="card"><h2>Groceries</h2><div class="row-actions"><input id="new-grocery" class="field grow" maxlength="120" placeholder="Milk, bananas, chicken…"><button class="button" id="add-grocery">Add</button></div>${state.groceries.map((g,i)=>`<div class="grocery-line"><label class="task"><input type="checkbox" data-grocery="${i}" ${g.done?'checked':''}><span>${esc(g.label)}</span></label><button class="icon-button" data-remove-grocery="${i}">×</button></div>`).join('')}<div class="row-actions"><button class="button secondary" id="copy-anylist">Copy for AnyList</button></div><p class="subtle">Paste copied items into AnyList. This is not automatic syncing.</p></div>${supplies()}${inbox()}`}
function routines(){return week()+sunday()+reset()}
function extras(){return collections()+more()+`<div class="card"><h3>Saved Scriptures</h3>${state.savedVerses.length?state.savedVerses.map(ref=>`<p>♡ ${esc(ref)}</p>`).join(''):'<p class="subtle">Save a Morning Grace verse to find it here.</p>'}<p class="subtle">Home Sweet Home 3.0 · Your data stays on this device unless you export it.</p></div>`}
function plan3(){return plan()+calendar()}
function copyText(t){if(navigator.clipboard&&window.isSecureContext)return navigator.clipboard.writeText(t).then(()=>alert('Copied!')).catch(()=>prompt('Copy this text:',t));prompt('Copy this text:',t)}

function render(){document.getElementById('today-label').textContent=new Intl.DateTimeFormat('en-US',{weekday:'long',month:'long',day:'numeric'}).format(new Date());document.getElementById('app').innerHTML=({home,plan3,lists,routines,extras}[tab]||home)();document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab))}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;
if(b.id==='minimum'){state.minimum=!state.minimum;save();render();return}
if(b.id==='save-verse'){const ref=verseToday()[0];state.savedVerses=state.savedVerses.includes(ref)?state.savedVerses.filter(x=>x!==ref):[...state.savedVerses,ref];save();render();return}
if(b.id==='copy-verse'){const v=verseToday();copyText(`${v[1]} — ${v[0]} (KJV)\n\n${v[3]}\n\nPrayer: ${v[4]}`);return}
if(b.id==='capture-add'){const x=document.getElementById('capture-input');if(x.value.trim()){state.capture.push({label:x.value.trim(),done:false});save();render()}return}
if(b.hasAttribute('data-remove-capture')){state.capture.splice(Number(b.dataset.removeCapture),1);save();render();return}
if(b.id==='supply-add'){const x=document.getElementById('supply-input');if(x.value.trim()){state.supplies.push({label:x.value.trim(),status:'stocked'});save();render()}return}
if(b.hasAttribute('data-supply-remove')){state.supplies.splice(Number(b.dataset.supplyRemove),1);save();render();return}
if(b.hasAttribute('data-supply-grocery')){const x=state.supplies[Number(b.dataset.supplyGrocery)];if(x&&!state.groceries.some(g=>g.label.toLowerCase()===x.label.toLowerCase())){state.groceries.push({label:x.label,done:false});save()}render();return}
if(b.id==='copy-anylist'){copyText(state.groceries.filter(x=>!x.done).map(x=>x.label).join('\n')||'Your grocery list is empty.');return}
if(b.hasAttribute('data-add-collection')){const type=b.dataset.addCollection,x=document.getElementById(type+'-input');if(x.value.trim()){state[type].push({label:x.value.trim(),done:false});save();render()}return}
if(b.hasAttribute('data-collection-remove')){const [type,i]=b.dataset.collectionRemove.split(':');state[type].splice(Number(i),1);save();render();return}
});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.tab){tab=b.dataset.tab;render();scrollTo(0,0)}else if(b.hasAttribute('data-day')){selectedDay=Number(b.dataset.day);render()}else if(b.id==='add-task'){const label=prompt('What task would you like to add?');if(label?.trim()){state.extra.push({id:Date.now().toString(36)+Math.random().toString(36).slice(2,6),day:selectedDay,label:label.trim().slice(0,120)});save();render()}}else if(b.id==='add-grocery'){const el=document.getElementById('new-grocery');if(el.value.trim()){state.groceries.push({label:el.value.trim().slice(0,120),done:false});save();render()}}else if(b.hasAttribute('data-remove-grocery')){state.groceries.splice(Number(b.dataset.removeGrocery),1);save();render()}else if(b.id==='add-event'){const date=document.getElementById('event-date').value,label=document.getElementById('event-label').value.trim();if(date&&label){state.events.push({id:Date.now().toString(36),date,label:label.slice(0,100)});save();render()}}else if(b.hasAttribute('data-remove-event')){state.events=state.events.filter(x=>x.id!==b.dataset.removeEvent);save();render()}else if(b.id==='save-meals'){document.querySelectorAll('[data-meal]').forEach(x=>state.meals[Number(x.dataset.meal)]=x.value.slice(0,200));save();alert('Meal plan saved!')}else if(b.id==='save-notes'){state.notes=document.getElementById('notes').value;save();alert('Notes saved!')}else if(b.id==='export'){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='home-sweet-home-backup-'+isoDate(new Date())+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}else if(b.id==='import'){document.getElementById('import-file').click()}else if(b.id==='clear'&&confirm('Erase all checklists, projects, meals and notes on this device?')){state=blank();save();render()}});
document.addEventListener('change',async e=>{const x=e.target;if(x.dataset.capture!==undefined){state.capture[Number(x.dataset.capture)].done=x.checked;save();render()}else if(x.dataset.supplyStatus!==undefined){state.supplies[Number(x.dataset.supplyStatus)].status=x.value;save()}else if(x.dataset.collectionCheck){const [type,i]=x.dataset.collectionCheck.split(':');state[type][Number(i)].done=x.checked;save();render()}else if(x.dataset.check){state.checks[x.dataset.check]=x.checked;save();render()}else if(x.hasAttribute('data-grocery')){state.groceries[Number(x.dataset.grocery)].done=x.checked;save();render()}else if(x.dataset.project){state.projects[x.dataset.project]=x.checked;save();render()}else if(x.dataset.maint){state.maintenance[x.dataset.maint]=x.checked;save();render()}else if(x.id==='import-file'&&x.files?.[0]){try{const obj=JSON.parse(await x.files[0].text());if(!obj||typeof obj!=='object'||Array.isArray(obj))throw Error('Invalid file');if(!confirm('Replace your current app data with this backup?'))return;state={...blank(),...obj,groceries:Array.isArray(obj.groceries)?obj.groceries:[],events:Array.isArray(obj.events)?obj.events:[]};save();render()}catch(err){alert('Could not import that backup file.')}}});
render();if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js').catch(()=>{});
